// ═══ AGENTS DATA (many realistic healthcare use cases) ═══
const agents = [
  // DENTAL
  {sector:'dental',icon:'🦷',sf:'Dentaire',se:'Dental',cat:'pec',cf:'Prise en charge',ce:'Prior Auth',n:{fr:'Envoi automatique des devis prothétiques aux mutuelles',en:'Auto-send prosthetic quotes to insurers'},d:{fr:'Dossier de prise en charge monté automatiquement avec codes CCAM, radiographies et plan de traitement. Envoi aux mutuelles via flux EDI. Accord obtenu en 48h au lieu de 12 jours. 47 prothèses traitées cette semaine, 0 rejet pour pièce manquante.',en:'Prior auth file auto-assembled with CCAM codes, X-rays and treatment plan. Sent to insurers via EDI. Approval in 48h instead of 12 days. 47 prosthetics processed this week, 0 rejections for missing documents.'},m:'-70% saisie',c:'#dcfce7',tc:'#166534'},
  {sector:'dental',icon:'🦷',sf:'Dentaire',se:'Dental',cat:'tp',cf:'Tiers-payant',ce:'Third-party',n:{fr:'Gestion complète du tiers-payant dentaire',en:'Full dental third-party payment management'},d:{fr:'Vérification droits AMO/AMC avant chaque acte. Télétransmission SESAM-Vitale, suivi retours NOEMIE, identification des rejets et correction automatique. Sur 2 340 actes ce mois, 99.1% first-pass rate. Gain de 2h45 par jour pour le secrétariat.',en:'AMO/AMC eligibility check before each procedure. SESAM-Vitale e-transmission, NOEMIE return tracking, rejection ID and auto-correction. 2,340 procedures this month, 99.1% first-pass rate. 2h45 saved daily for front desk.'},m:'99.1% first-pass',c:'#dbeafe',tc:'#1e40af'},
  {sector:'dental',icon:'🦷',sf:'Dentaire',se:'Dental',cat:'recouv',cf:'Recouvrement',ce:'Collection',n:{fr:'Relance automatique des impayés dentaires',en:'Auto follow-up on dental unpaid claims'},d:{fr:'Détection des factures impayées à J+30, J+60, J+90. Envoi de relances personnalisées par email puis SMS. Escalade automatique vers le gestionnaire contentieux après 3 relances sans réponse. Taux de recouvrement passé de 62% à 89% en 3 mois.',en:'Unpaid invoice detection at D+30, D+60, D+90. Personalized follow-ups via email then SMS. Auto escalation to disputes manager after 3 unanswered attempts. Collection rate from 62% to 89% in 3 months.'},m:'÷3 délai recouv.',c:'#ffedd5',tc:'#9a3412'},
  {sector:'dental',icon:'🦷',sf:'Dentaire',se:'Dental',cat:'verif',cf:'Vérification',ce:'Verification',n:{fr:'Contrôle des droits patient avant chaque rendez-vous',en:'Patient eligibility check before every appointment'},d:{fr:'24h avant chaque RDV, l\'agent vérifie la couverture AMO et AMC du patient. En cas d\'anomalie (carte expirée, changement de mutuelle, CMU non renouvelée), alerte envoyée à l\'accueil avec les actions à mener. 12 anomalies détectées cette semaine évitant des impayés.',en:'24h before each appointment, agent checks AMO and AMC coverage. If anomaly (expired card, insurer change, unrewewed CMU), alert sent to front desk with actions. 12 anomalies caught this week preventing unpaid claims.'},m:'< 2s par vérif.',c:'#f3e8ff',tc:'#6b21a8'},

  // OPTICAL
  {sector:'optical',icon:'👓',sf:'Optique',se:'Optical',cat:'devis',cf:'Devis',ce:'Quotes',n:{fr:'Devis tiers-payant optique en 5 secondes',en:'Optical third-party quote in 5 seconds'},d:{fr:'Lecture carte mutuelle, interrogation OptoAMC, calcul instantané du reste à charge selon le panier choisi (100% Santé, Classe A, Classe B). Devis envoyé au patient par email avec détail remboursement SS + mutuelle. 380 devis générés cette semaine chez Jimmy Fairly Opticien.',en:'Mutual card reading, OptoAMC query, instant out-of-pocket calc per basket (100% Santé, Class A, B). Quote emailed to patient with SS + insurer breakdown. 380 quotes generated this week at Jimmy Fairly Optician.'},m:'< 5s par devis',c:'#cffafe',tc:'#155e75'},
  {sector:'optical',icon:'👓',sf:'Optique',se:'Optical',cat:'tp',cf:'Tiers-payant',ce:'Third-party',n:{fr:'Rapprochement bancaire automatisé virements optiques',en:'Auto bank reconciliation for optical transfers'},d:{fr:'L\'agent matche les virements AMO et AMC avec les factures correspondantes. Identification des écarts, sous-paiements et virements non affectés. Rapprochement de 1 200 lignes traité en 8 minutes au lieu de 4h. Écart moyen détecté : 0.3%.',en:'Agent matches AMO and AMC transfers with corresponding invoices. Gap identification, underpayments and unmatched transfers. 1,200 lines reconciled in 8 min instead of 4h. Average gap detected: 0.3%.'},m:'-85% temps',c:'#dbeafe',tc:'#1e40af'},
  {sector:'optical',icon:'👓',sf:'Optique',se:'Optical',cat:'compliance',cf:'100% Santé',ce:'100% Santé',n:{fr:'Vérification conformité panier 100% Santé',en:'100% Santé basket compliance check'},d:{fr:'Avant chaque vente, l\'agent vérifie que l\'équipement proposé respecte les obligations du panier 100% Santé : monture < 30€, verres dans la liste LPP, conformité du devis normalisé. Alerte si non-conformité détectée. 0 anomalie ARS depuis le déploiement.',en:'Before each sale, agent checks equipment meets 100% Santé basket: frame < €30, lenses in LPP list, standardized quote compliance. Alert if non-compliance. 0 ARS anomalies since deployment.'},m:'100% conformité',c:'#dcfce7',tc:'#166534'},
  {sector:'optical',icon:'👓',sf:'Optique',se:'Optical',cat:'plateforme',cf:'Plateforme',ce:'Platform',n:{fr:'Synchronisation multi-plateformes OptoAMC et Viamedis',en:'Multi-platform OptoAMC & Viamedis sync'},d:{fr:'Connexion simultanée à OptoAMC et Viamedis pour croiser les droits du patient avec les deux plateformes. Détection automatique de la plateforme de référence selon la mutuelle. Élimination de la double saisie. 100% des mutuelles couvertes sur le réseau.',en:'Simultaneous OptoAMC and Viamedis connection to cross-check patient rights. Auto-detection of reference platform per insurer. Double entry eliminated. 100% of insurers covered on the network.'},m:'0 double saisie',c:'#fce7f3',tc:'#9d174d'},

  // AUDIO
  {sector:'audio',icon:'👂',sf:'Audio',se:'Audio',cat:'pec',cf:'Prise en charge',ce:'Prior Auth',n:{fr:'Montage automatique des dossiers audioprothèse',en:'Auto assembly of hearing aid prior auth files'},d:{fr:'Récupération prescription ORL, audiogramme, devis normalisé LPP. Assemblage du dossier complet et envoi CPAM + mutuelle. Suivi des délais de réponse, relance automatique à J+15. Temps de montage passé de 45min à 6min par dossier.',en:'ORL prescription retrieval, audiogram, standardized LPP quote. Complete file assembly and CPAM + insurer submission. Response tracking, auto follow-up at D+15. Assembly time from 45min to 6min per file.'},m:'-75% montage',c:'#dcfce7',tc:'#166534'},
  {sector:'audio',icon:'👂',sf:'Audio',se:'Audio',cat:'suivi',cf:'Suivi patient',ce:'Patient tracking',n:{fr:'Suivi complet du parcours audioprothétique',en:'Complete hearing aid patient journey tracking'},d:{fr:'Rappels automatiques : période d\'essai 30j, RDV de réglage à M+1/M+3/M+6, renouvellement à 4 ans. SMS/email personnalisés. Taux de rétention patient amélioré de 40% depuis le déploiement. 234 patients suivis activement.',en:'Auto reminders: 30-day trial, adjustment at M+1/M+3/M+6, 4-year renewal. Personalized SMS/email. Patient retention improved 40% since deployment. 234 patients actively tracked.'},m:'+40% rétention',c:'#fef3c7',tc:'#92400e'},

  // HOSPITAL
  {sector:'hospital',icon:'🏥',sf:'Hôpital',se:'Hospital',cat:'admission',cf:'Admissions',ce:'Admissions',n:{fr:'Pré-admission digitalisée avec vérification droits',en:'Digital pre-admission with eligibility verification'},d:{fr:'Le patient reçoit un lien 48h avant son admission. L\'agent collecte les pièces (carte Vitale, mutuelle, courrier médecin), vérifie les droits AMO/AMC en temps réel et pré-remplit le dossier administratif. Temps d\'accueil réduit de 25min à 8min. Déployé au CHU de Bordeaux.',en:'Patient receives a link 48h before admission. Agent collects documents (Vitale card, insurance, GP letter), verifies AMO/AMC rights in real time and pre-fills the admin file. Reception time from 25min to 8min. Deployed at CHU Bordeaux.'},m:'-60% accueil',c:'#fce7f3',tc:'#9d174d'},
  {sector:'hospital',icon:'🏥',sf:'Hôpital',se:'Hospital',cat:'facturation',cf:'Facturation T2A',ce:'T2A billing',n:{fr:'Optimisation du codage GHM/GHS et détection sous-codages',en:'GHM/GHS coding optimization and under-coding detection'},d:{fr:'L\'agent analyse les comptes-rendus d\'hospitalisation, suggère les diagnostics CIM-10 et actes CCAM manquants. Détection de 847 sous-codages sur le dernier trimestre, soit +12% de valorisation des séjours. Audit trail complet pour les contrôles T2A.',en:'Agent analyzes discharge summaries, suggests missing ICD-10 diagnoses and CCAM procedures. 847 under-codings detected last quarter, +12% stay valorization. Complete audit trail for T2A audits.'},m:'+12% valorisation',c:'#dbeafe',tc:'#1e40af'},
  {sector:'hospital',icon:'🏥',sf:'Hôpital',se:'Hospital',cat:'recouv',cf:'Recouvrement',ce:'Collection',n:{fr:'Recouvrement des restes à charge hospitaliers',en:'Hospital out-of-pocket collection'},d:{fr:'Identification automatique des RAC patients après liquidation CPAM et mutuelle. Envoi de factures, propositions d\'échéancier, relances graduées. Taux de recouvrement passé de 54% à 78%. Interface avec le Trésor Public pour les créances irrécouvrables.',en:'Auto identification of patient OOP after CPAM and insurer settlement. Invoice sending, payment plan proposals, graduated follow-ups. Collection rate from 54% to 78%. Treasury interface for bad debt.'},m:'-45% créances',c:'#ffedd5',tc:'#9a3412'},
  {sector:'hospital',icon:'🏥',sf:'Hôpital',se:'Hospital',cat:'parcours',cf:'Parcours',ce:'Pathway',n:{fr:'Coordination inter-services et transferts patients',en:'Cross-department coordination and patient transfers'},d:{fr:'Notification automatique du médecin traitant à l\'admission et à la sortie. Coordination avec les SSR pour les transferts, envoi du dossier médical synthétique. Suivi des délais de transfert : réduction de 30% du temps administratif de sortie.',en:'Auto GP notification at admission and discharge. SSR coordination for transfers, synthetic medical file sending. Transfer delay tracking: 30% admin time reduction at discharge.'},m:'-30% admin sortie',c:'#dcfce7',tc:'#166534'},

  // EHPAD
  {sector:'ehpad',icon:'🏠',sf:'EHPAD',se:'Nursing Home',cat:'admission',cf:'Admissions',ce:'Admissions',n:{fr:'Constitution automatique des dossiers APA et aide sociale',en:'Auto APA and social aid file assembly'},d:{fr:'L\'agent guide la famille dans la collecte des pièces (avis d\'imposition, certificat médical, GIR). Pré-remplissage des formulaires CERFA. Envoi automatique au Conseil Départemental. Suivi de l\'instruction et relance si délai dépassé. 80% de temps gagné sur la constitution.',en:'Agent guides family through document collection (tax notice, medical certificate, GIR). CERFA form pre-filling. Auto submission to Departmental Council. Instruction tracking and follow-up if delayed. 80% time saved on assembly.'},m:'-80% constitution',c:'#fce7f3',tc:'#9d174d'},
  {sector:'ehpad',icon:'🏠',sf:'EHPAD',se:'Nursing Home',cat:'facturation',cf:'Facturation',ce:'Billing',n:{fr:'Facturation mensuelle hébergement, dépendance et soins',en:'Monthly accommodation, dependency and care billing'},d:{fr:'Calcul automatique des trois tarifs (hébergement, dépendance, soins) selon le GIR et les décisions APA. Facturation différenciée aide sociale / reste à charge famille. Envoi automatique des factures. 0 erreur de facturation depuis 8 mois.',en:'Auto calculation of three rates (accommodation, dependency, care) per GIR and APA decisions. Differentiated social aid / family billing. Auto invoice sending. 0 billing errors for 8 months.'},m:'0 erreur facture',c:'#dbeafe',tc:'#1e40af'},
  {sector:'ehpad',icon:'🏠',sf:'EHPAD',se:'Nursing Home',cat:'suivi',cf:'Renouvellements',ce:'Renewals',n:{fr:'Alertes et renouvellement automatique des droits APA',en:'Auto APA rights renewal alerts and processing'},d:{fr:'Surveillance des dates d\'expiration APA pour chaque résident. Alerte à M-3, constitution automatique du dossier de renouvellement, envoi au CD. Aucune rupture de droits constatée depuis le déploiement. 156 résidents suivis.',en:'APA expiration date monitoring per resident. M-3 alert, auto renewal file assembly, CD submission. Zero rights gaps since deployment. 156 residents tracked.'},m:'0 rupture droits',c:'#fef3c7',tc:'#92400e'},

  // PHARMACY
  {sector:'pharma',icon:'💊',sf:'Pharmacie',se:'Pharmacy',cat:'tp',cf:'Tiers-payant',ce:'Third-party',n:{fr:'Traitement automatique des rejets SESAM-Vitale',en:'Auto SESAM-Vitale rejection processing'},d:{fr:'Analyse automatique de chaque rejet de télétransmission : identification de la cause (carte expirée, prescripteur non conventionné, doublon), correction et re-soumission. 92% des rejets corrigés sans intervention humaine. Réduction du stock de rejets de 340 à 28 en 6 semaines.',en:'Auto analysis of each e-transmission rejection: cause ID (expired card, non-approved prescriber, duplicate), correction and resubmission. 92% of rejections fixed without human intervention. Rejection backlog from 340 to 28 in 6 weeks.'},m:'-90% rejets',c:'#dbeafe',tc:'#1e40af'},
  {sector:'pharma',icon:'💊',sf:'Pharmacie',se:'Pharmacy',cat:'recouv',cf:'Recouvrement',ce:'Collection',n:{fr:'Suivi et relance des impayés mutuelles en officine',en:'Pharmacy insurer unpaid tracking and follow-up'},d:{fr:'Surveillance quotidienne des paiements AMC attendus. Détection des retards > 15 jours, envoi de relances automatiques aux organismes. Escalade contentieux après 3 relances. Taux de recouvrement amélioré de 35%. Gain estimé : 12 000€/an pour une officine moyenne.',en:'Daily AMC payment monitoring. Detection of delays > 15 days, auto follow-ups to organizations. Dispute escalation after 3 attempts. Collection rate improved 35%. Estimated gain: €12,000/year for average pharmacy.'},m:'+35% recouvré',c:'#ffedd5',tc:'#9a3412'},
  {sector:'pharma',icon:'💊',sf:'Pharmacie',se:'Pharmacy',cat:'compliance',cf:'Conformité',ce:'Compliance',n:{fr:'Vérification automatique de la conformité des ordonnances',en:'Auto prescription compliance verification'},d:{fr:'Contrôle systématique de chaque ordonnance : date de validité, prescripteur habilité, posologie conforme, interactions médicamenteuses, durée de traitement. Alerte pharmacien en cas d\'anomalie. 100% des ordonnances vérifiées, 23 alertes critiques ce mois.',en:'Systematic check of each prescription: validity date, authorized prescriber, dosage compliance, drug interactions, treatment duration. Pharmacist alert on anomaly. 100% prescriptions checked, 23 critical alerts this month.'},m:'100% vérifiées',c:'#f3e8ff',tc:'#6b21a8'},

  // PHARMA LABS
  {sector:'lab',icon:'🧬',sf:'Labo pharma',se:'Pharma Lab',cat:'regulatory',cf:'Réglementaire',ce:'Regulatory',n:{fr:'Veille réglementaire ANSM, EMA et HAS en continu',en:'Continuous ANSM, EMA & HAS regulatory monitoring'},d:{fr:'Surveillance 24/7 des publications ANSM, EMA, HAS et JO. Détection des modifications impactant les AMM en portefeuille. Alerte immédiate aux équipes réglementaires avec analyse d\'impact. 847 publications analysées ce trimestre, 12 alertes critiques émises.',en:'24/7 monitoring of ANSM, EMA, HAS and Official Journal publications. Detection of changes impacting portfolio MAs. Immediate alert to regulatory teams with impact analysis. 847 publications analyzed this quarter, 12 critical alerts issued.'},m:'24/7 veille',c:'#ffedd5',tc:'#9a3412'},
  {sector:'lab',icon:'🧬',sf:'Labo pharma',se:'Pharma Lab',cat:'pharma_vig',cf:'Pharmacovigilance',ce:'Pharmacovigilance',n:{fr:'Traitement automatisé des signalements d\'effets indésirables',en:'Automated adverse event report processing'},d:{fr:'Collecte des signalements multi-sources (médecins, patients, littérature), tri par gravité, pré-qualification MedDRA. Génération automatique des formulaires CIOMS I. Délai de traitement initial réduit de 72h à 4h. Conformité PSMF maintenue à 100%.',en:'Multi-source report collection (doctors, patients, literature), severity triage, MedDRA pre-qualification. Auto CIOMS I form generation. Initial processing from 72h to 4h. PSMF compliance maintained at 100%.'},m:'-65% traitement',c:'#fce7f3',tc:'#9d174d'},
  {sector:'lab',icon:'🧬',sf:'Labo pharma',se:'Pharma Lab',cat:'market',cf:'Market Access',ce:'Market Access',n:{fr:'Analyse comparative des dossiers de remboursement HAS/CEPS',en:'Comparative reimbursement dossier analysis HAS/CEPS'},d:{fr:'Analyse automatique des avis de la Commission de Transparence, comparaison des ASMR obtenus par les concurrents, identification des arguments clés. Aide à la constitution du dossier médico-économique pour les négociations CEPS. Efficacité des dossiers améliorée de 25%.',en:'Auto analysis of Transparency Committee opinions, competitor ASMR comparison, key argument identification. Medical-economic dossier preparation for CEPS negotiations. Dossier effectiveness improved 25%.'},m:'+25% efficacité',c:'#cffafe',tc:'#155e75'},

  // BIO LABS
  {sector:'bio',icon:'🔬',sf:'Labo bio',se:'Medical Lab',cat:'facturation',cf:'Facturation',ce:'Billing',n:{fr:'Cotation NABM automatique avec gestion des cumuls',en:'Auto NABM coding with cumulation management'},d:{fr:'Application automatique des codes NABM selon les analyses prescrites. Gestion des règles de cumul complexes (B, BHN, P), application des plafonds quotidiens et des dérogations. 0 erreur de cotation depuis le déploiement sur 18 000 analyses/mois.',en:'Auto NABM code application per prescribed tests. Complex cumulation rule management (B, BHN, P), daily cap application and exceptions. 0 coding errors since deployment on 18,000 tests/month.'},m:'0 erreur cotation',c:'#dbeafe',tc:'#1e40af'},
  {sector:'bio',icon:'🔬',sf:'Labo bio',se:'Medical Lab',cat:'preanalytique',cf:'Pré-analytique',ce:'Pre-analytical',n:{fr:'Détection et gestion des non-conformités pré-analytiques',en:'Pre-analytical non-conformity detection and management'},d:{fr:'Détection automatique des anomalies : tube incorrect, volume insuffisant, délai d\'acheminement dépassé. Notification immédiate au prescripteur et au patient pour reconvocation. Traçabilité complète pour l\'accréditation COFRAC. -50% de reconvocations tardives.',en:'Auto anomaly detection: incorrect tube, insufficient volume, exceeded transport time. Immediate prescriber and patient notification for recall. Complete traceability for COFRAC accreditation. -50% late recalls.'},m:'-50% retards',c:'#fef3c7',tc:'#92400e'},

  // ORTHO
  {sector:'ortho',icon:'🦿',sf:'Orthodontie',se:'Orthodontics',cat:'devis',cf:'Devis',ce:'Quotes',n:{fr:'Devis orthodontique normalisé multi-semestres',en:'Multi-semester standardized orthodontic quotes'},d:{fr:'Génération automatique des devis conformes CCAM avec calcul du reste à charge par semestre sur 6 semestres de traitement. Intégration des plafonds de prise en charge SS selon l\'âge du patient. Envoi automatique au patient et à la mutuelle. -60% de temps de devis.',en:'Auto CCAM-compliant quote generation with per-semester out-of-pocket calc over 6 treatment semesters. Integration of SS coverage caps per patient age. Auto sending to patient and insurer. -60% quoting time.'},m:'-60% temps devis',c:'#cffafe',tc:'#155e75'},
  {sector:'ortho',icon:'🦿',sf:'Orthodontie',se:'Orthodontics',cat:'pec',cf:'Entente préalable',ce:'Prior agreement',n:{fr:'Gestion automatique des ententes préalables CPAM',en:'Auto CPAM prior agreement management'},d:{fr:'Constitution du dossier d\'entente préalable avec toutes les pièces (radio panoramique, moulages, photo, plan de traitement). Envoi à la CPAM, suivi du délai de 15 jours, relance automatique. Taux d\'acceptation : 95%. 0 rejet pour dossier incomplet.',en:'Prior agreement file assembly with all documents (panoramic X-ray, impressions, photo, treatment plan). CPAM submission, 15-day tracking, auto follow-up. Acceptance rate: 95%. 0 rejections for incomplete files.'},m:'95% acceptation',c:'#dcfce7',tc:'#166534'},
  {sector:'ortho',icon:'🦿',sf:'Orthodontie',se:'Orthodontics',cat:'suivi',cf:'Suivi traitement',ce:'Treatment tracking',n:{fr:'Planification et suivi des 6 semestres de traitement',en:'6-semester treatment planning and tracking'},d:{fr:'Suivi automatisé de chaque semestre : rappels de RDV, alertes de renouvellement de prise en charge, facturation semestrielle. Détection des patients à risque d\'abandon. Taux d\'abandon réduit de 40% grâce au suivi proactif.',en:'Automated semester tracking: appointment reminders, coverage renewal alerts, semester billing. At-risk patient detection. Dropout rate reduced 40% through proactive tracking.'},m:'-40% abandons',c:'#fef3c7',tc:'#92400e'},

  // MORE CROSS-CUTTING
  {sector:'dental',icon:'🦷',sf:'Dentaire',se:'Dental',cat:'facturation',cf:'Facturation',ce:'Billing',n:{fr:'Facturation automatique des actes CCAM et NGAP',en:'Auto CCAM and NGAP procedure billing'},d:{fr:'À la fin de chaque journée, l\'agent vérifie que tous les actes réalisés sont facturés avec le bon code CCAM ou NGAP, applique les modificateurs (urgence, nuit, férié) et lance la télétransmission. 0 acte oublié, 0 erreur de codage détecté sur 1 890 actes ce mois.',en:'At end of each day, agent verifies all procedures are billed with correct CCAM or NGAP code, applies modifiers (emergency, night, holiday) and launches e-transmission. 0 forgotten procedures, 0 coding errors on 1,890 acts this month.'},m:'0 oubli d\'acte',c:'#dbeafe',tc:'#1e40af'},
  {sector:'hospital',icon:'🏥',sf:'Hôpital',se:'Hospital',cat:'compliance',cf:'Conformité CPOM',ce:'CPOM compliance',n:{fr:'Suivi des indicateurs CPOM et reporting ARS',en:'CPOM indicator tracking and ARS reporting'},d:{fr:'Collecte automatique des données d\'activité, calcul des indicateurs CPOM (taux d\'occupation, DMS, IPDMS), génération des tableaux de bord pour les dialogues de gestion ARS. Rapport mensuel envoyé automatiquement à la direction.',en:'Auto activity data collection, CPOM indicator calculation (occupancy rate, LOS, IPLOS), dashboard generation for ARS management dialogues. Monthly report auto-sent to management.'},m:'Auto reporting',c:'#f3e8ff',tc:'#6b21a8'},
  {sector:'pharma',icon:'💊',sf:'Pharmacie',se:'Pharmacy',cat:'stock',cf:'Stock & commandes',ce:'Stock & orders',n:{fr:'Alerte ruptures de stock et gestion des commandes dépannage',en:'Stock-out alerts and emergency order management'},d:{fr:'Surveillance temps réel des niveaux de stock. Alerte quand un médicament à forte rotation passe sous le seuil critique. Commande dépannage automatique chez le grossiste ou proposition de substitution. 0 rupture non anticipée depuis 4 mois.',en:'Real-time stock level monitoring. Alert when high-turnover medication drops below critical threshold. Auto emergency order to wholesaler or substitution proposal. 0 unanticipated stock-outs for 4 months.'},m:'0 rupture',c:'#dcfce7',tc:'#166534'},
  {sector:'optical',icon:'👓',sf:'Optique',se:'Optical',cat:'recouv',cf:'Recouvrement',ce:'Collection',n:{fr:'Suivi des impayés réseau optique multi-magasins',en:'Multi-store optical network unpaid tracking'},d:{fr:'Dashboard centralisé pour les réseaux d\'opticiens : impayés par magasin, par mutuelle, par ancienneté. Relances automatiques, scoring des dossiers par probabilité de recouvrement. Réseau de 45 magasins : gain de 180 000€ en restes à recouvrer sur 6 mois.',en:'Centralized dashboard for optician networks: unpaid by store, insurer, age. Auto follow-ups, file scoring by collection probability. 45-store network: €180,000 recovered in 6 months.'},m:'180K€ recouvrés',c:'#ffedd5',tc:'#9a3412'},
  {sector:'ehpad',icon:'🏠',sf:'EHPAD',se:'Nursing Home',cat:'coordination',cf:'Coordination',ce:'Coordination',n:{fr:'Communication automatique avec les familles et les tuteurs',en:'Auto communication with families and guardians'},d:{fr:'Notifications automatiques aux familles : facturation mensuelle, renouvellement APA, changement de GIR, événements de vie. Réponse automatique aux demandes courantes (copie de facture, attestation). Satisfaction familles améliorée de 50%.',en:'Auto family notifications: monthly billing, APA renewal, GIR change, life events. Auto response to common requests (invoice copy, certificate). Family satisfaction improved 50%.'},m:'+50% satisfaction',c:'#f3e8ff',tc:'#6b21a8'},
  {sector:'bio',icon:'🔬',sf:'Labo bio',se:'Medical Lab',cat:'tp',cf:'Tiers-payant',ce:'Third-party',n:{fr:'Télétransmission et suivi des retours NOEMIE',en:'E-transmission and NOEMIE return tracking'},d:{fr:'Télétransmission SESAM-Vitale optimisée avec batch quotidien. Analyse automatique des retours NOEMIE : détection anomalies, rejets, paiements partiels. Correction et re-soumission. First-pass rate maintenu à 99.8% sur 45 000 dossiers/mois.',en:'Optimized SESAM-Vitale e-transmission with daily batch. Auto NOEMIE return analysis: anomaly detection, rejections, partial payments. Correction and resubmission. 99.8% first-pass rate on 45,000 files/month.'},m:'99.8% first-pass',c:'#dbeafe',tc:'#1e40af'},
];

const sectors = [
  {id:'all',icon:'',fr:'Tous',en:'All'},
  {id:'dental',icon:'🦷',fr:'Dentaire',en:'Dental'},
  {id:'optical',icon:'👓',fr:'Optique',en:'Optical'},
  {id:'audio',icon:'👂',fr:'Audio',en:'Audio'},
  {id:'hospital',icon:'🏥',fr:'Hôpital',en:'Hospital'},
  {id:'ehpad',icon:'🏠',fr:'EHPAD',en:'Nursing Home'},
  {id:'pharma',icon:'💊',fr:'Pharmacie',en:'Pharmacy'},
  {id:'lab',icon:'🧬',fr:'Labo pharma',en:'Pharma Lab'},
  {id:'bio',icon:'🔬',fr:'Labo bio',en:'Medical Lab'},
  {id:'ortho',icon:'🦿',fr:'Orthodontie',en:'Orthodontics'},
];

const ucTypes = [
  {id:'all',fr:'Tous',en:'All'},
  {id:'pec',fr:'Prise en charge',en:'Prior Auth'},
  {id:'tp',fr:'Tiers-payant',en:'Third-party'},
  {id:'recouv',fr:'Recouvrement',en:'Collection'},
  {id:'facturation',fr:'Facturation',en:'Billing'},
  {id:'devis',fr:'Devis',en:'Quotes'},
  {id:'verif',fr:'Vérification',en:'Verification'},
  {id:'suivi',fr:'Suivi',en:'Tracking'},
  {id:'admission',fr:'Admissions',en:'Admissions'},
  {id:'compliance',fr:'Conformité',en:'Compliance'},
  {id:'regulatory',fr:'Réglementaire',en:'Regulatory'},
  {id:'pharma_vig',fr:'Pharmacovigilance',en:'Pharmacovigilance'},
  {id:'market',fr:'Market Access',en:'Market Access'},
];

const tools = [
  {i:'🔌',f:'Connecteurs natifs',e:'Native connectors',df:'REST, SOAP, EDI, HL7 FHIR',de:'REST, SOAP, EDI, HL7 FHIR'},
  {i:'🌐',f:'Navigation autonome',e:'Autonomous browsing',df:'Portails sans API couverts',de:'Portals without API covered'},
  {i:'📊',f:'Rapprochement',e:'Reconciliation',df:'Match virements / factures',de:'Match transfers / invoices'},
  {i:'📋',f:'Nomenclatures',e:'Medical coding',df:'CCAM, NGAP, NABM, LPP, GHM',de:'CCAM, NGAP, NABM, LPP, GHM'},
  {i:'📧',f:'Email & SMS',e:'Email & SMS',df:'Relances, notifications',de:'Follow-ups, notifications'},
  {i:'🔒',f:'HDS',e:'HDS certified',df:'Hébergement certifié santé',de:'Certified health hosting'},
  {i:'📅',f:'Planification',e:'Scheduling',df:'Cron, webhook, trigger',de:'Cron, webhook, trigger'},
  {i:'🔗',f:'API ouverte',e:'Open API',df:'Connectez vos propres outils',de:'Connect your own tools'},
  {i:'📈',f:'Dashboards',e:'Dashboards',df:'Performance, anomalies',de:'Performance, anomalies'},
];

const cardColors = ['#e8f5e9','#e3f2fd','#fce4ec','#fff3e0','#f3e5f5','#e0f7fa','#fff8e1','#f1f8e9','#e8eaf6'];
